# Generated by Django 5.1.1 on 2024-10-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BehLabNet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyects",
            name="key_words",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
